// Computes the real ratio (width / height) of each print's
// "aucun.jpg" photo, and writes it to data/imageRatios.generated.ts.
//
// Why: the gallery (JustifiedGallery.tsx) needs to know each photo's
// real proportions to build its justified rows. Without this script,
// that information would only be known once the image has loaded in
// the visitor's browser — causing a small visual reflow on first
// display. Computing it here, once, means the information is already
// correct from the server-rendered output.
//
// Run automatically before "npm run dev" and "npm run build" (see the
// "predev"/"prebuild" scripts in package.json) — no need to run it by
// hand, except to force an immediate update.

import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const DOSSIER_TIRAGES = path.join(process.cwd(), "public", "images", "tirages");
const FICHIER_SORTIE = path.join(process.cwd(), "data", "imageRatios.generated.ts");

async function calculerRatios() {
  const entrees = await readdir(DOSSIER_TIRAGES, { withFileTypes: true });
  const dossiers = entrees.filter((entree) => entree.isDirectory());

  const ratios = {};
  for (const dossier of dossiers) {
    const cheminPhoto = path.join(DOSSIER_TIRAGES, dossier.name, "aucun.jpg");
    try {
      const { width, height } = await sharp(cheminPhoto).metadata();
      if (!width || !height) {
        throw new Error("unknown dimensions");
      }
      ratios[`/images/tirages/${dossier.name}`] = Number((width / height).toFixed(4));
    } catch (erreur) {
      console.warn(
        `⚠️  calculer-ratios: no valid "aucun.jpg" in "${dossier.name}" (${erreur.message}), skipped.`
      );
    }
  }

  const lignes = Object.entries(ratios)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([cle, valeur]) => `  "${cle}": ${valeur},`)
    .join("\n");

  const contenu = `// Auto-generated by scripts/calculer-ratios.mjs — do not edit by hand.
// Re-run before every "npm run dev" / "npm run build" (see package.json).
//
// Maps a print's \`imageFolder\` (data/prints.ts) to the real
// width/height ratio of its "aucun.jpg" file.
export const RATIOS_IMAGES: Record<string, number> = {
${lignes}
};
`;

  await writeFile(FICHIER_SORTIE, contenu, "utf8");
  console.log(
    `✓ calculer-ratios: ${Object.keys(ratios).length} tirage(s) → ${path.relative(process.cwd(), FICHIER_SORTIE)}`
  );
}

calculerRatios();
